# Generated by Django 4.0.4 on 2022-08-04 10:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker', '0002_alter_file_saved_file_alter_file_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='saved_file',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='zip_file',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
    ]
