# Generated by Django 4.0.4 on 2022-08-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker', '0002_file_file_name_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='saved_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
